name: kotlin_scope_function_example
publish_to: none
description: Demonstrates how to use the kotlin_scope_function plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  velocity_x: any
  faker: ^2.0.0
  flutter_lorem: ^2.0.0
  cupertino_icons: ^1.0.2
  get:
  flutter:
    sdk: flutter
  gredu_common:
    path: ../

flutter: 
  uses-material-design: true

get_cli: 
  sub_folder: false

